name: Publish

on:
  push:
    branches: [main]
    tags: ['v*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    permissions:
      contents: write
      packages: read
    uses: jruk8/plugin-conventions/.github/workflows/publish.yml@v1.3.5
    secrets: inherit
